development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DB_PORT'] %>                
  pool: <%= ENV['DATABASE_POOL'] %>
  timeout: 5000
 


production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV['DATABASE_POOL'] %>
  port: <%= ENV['DB_PORT'] %>
  timeout: 5000
